### PR TITLE
Journal fixes

### PR DESCRIPTION
**Pull request by annatraussnig**

### CODE REVIEW

**Review by patrickvenetz — APPROVED** [review]
LGTM

**Comment by patrickvenetz** [comment]
Did Oli as to count char for "Moderation" section, too?

Bildschirmfoto 2022-09-19 um 19 39 16

**Comment by annatraussnig** [comment]
nope. just the "author" part

**Comment by patrickvenetz** [comment]
Loffly.

**Comment by patrickvenetz** [comment]
Still, LGTM.

(Maybe add a prosaic or screenshötteled list of fixes in description for future usses?)

**Review by patrickvenetz — APPROVED** [review]

**Pull request merged**
