### PR TITLE
Bump required Node Version to 16

### PR DESCRIPTION
**Pull request by trm217**
## Description

Bumping the node-version will increase the performance of the developer environments.
Node 16 is the first Node LTS Version that has an official ARM build for MacOS thus especially people with Apple Silicon processors will benefit from this upgrade.

### CODE REVIEW

**Comment by trm217** [comment]
@tpreusse 
Seems the tests are indeed stuck again. I tried using `yarn test --graph` to find a possible circular dependency, but I wan't able to find one. Would you mind looking into it sometime?

**Comment by tpreusse** [comment]
@trm217 seems to be a turbo issue: https://github.com/vercel/turborepo/issues/766

**Comment by trm217** [comment]
Lot's of Turbo related issues at the moment :/

**Comment by trm217** [comment]
the mentioned issue was closed, but after bumping to turbo@1.1.5 it seems the error still persists

**Pull request closed without merging**
